backend:
  name: git-gateway
  branch: master
  publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "homepage" 
    label: "HomePage"
    folder: "content/homepage"
    create: false
    slug: "{{year}}"
    widget: "object"
    identifier_field: label
    fields:
      - label: "Banner"
        name: "banner"
        widget: "object"
        fields:
          - {name: "bannerTitle", label: "Banner Title", required: true, widget: "text" }
          - {label: "OfferBanner", name: "offerBanner", widget: "string"}
          - {label: "DescriptionBanner", name: "descriptionBanner", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
      - label: "Looking For Section"
        name: "lookingForSection"
        widget: "object"
        fields:
          - {name: "title", label: "Title", required: true, widget: "text" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image", name: "image1", widget: "image"}
          - {name: "title2", label: "Title2", required: true, widget: "text" }
          - {label: "Image2", name: "image2", widget: "image"}
          - {name: "title3", label: "Title3", required: true, widget: "text" }
          - {label: "Image3", name: "image3", widget: "image"}
      - label: "Destinations"
        name: "destinations"
        widget: "object"
        fields:
          - {name: "title", label: "Title", required: true, widget: "text" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image", name: "dimage", widget: "image"}
      - label: "Destinations2"
        name: "destinations2"
        widget: "object"
        fields:
          - {name: "title", label: "Title", required: true, widget: "text" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
      - label: "Destinations3"
        name: "destinations3"
        widget: "object"
        fields:
          - {name: "title", label: "Title", required: true, widget: "text" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
      - label: "Destinations4"
        name: "destinations4"
        widget: "object"
        fields:
          - {name: "d4title", label: "Title", required: true, widget: "text" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
      - label: "Book Now"
        name: "bookNow"
        widget: "object"
        fields:
          - {name: "title", label: "Title", required: true, widget: "text" }
          - {label: "Description1", name: "description1", widget: "string"}
          - {label: "Description2", name: "description2", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
  - name: "homepageSeo" 
    label: "HomePageSeo"
    folder: "content/homepage"
    create: false
    slug: "seo-homepage"
    identifier_field: label
    fields:
      - {name: "title", label: "Title", required: true, widget: "text" }
      - {label: "Url", name: "url", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "destinations"
    label: "Destinations"
    description: "Destinations List"
    files:
      - label: "Destination"
        name: "destination"
        file: "content/destination"
        fields:
          - label: "Destination List"
            name: "destinationList"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "text"}
              - {label: "Section1 Title", name: "section1Title", widget: "text"}
              - label:  "Section1"
                name:   "section1"
                widget: "list"
                fields: 
                   - {label: "Description", name: "description", widget: "text"}
                 
              
              