backend:
  name: git-gateway
  branch: master
  publish_mode: editorial_workflow
media_folder: "./public" # Media files will be stored in the repo under static/images/uploads
public_folder: "./public" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "homepage" 
    label: "HomePage"
    folder: "content/homepage"
    create: true
    slug: "{{year}}"
    widget: "object"
    fields:
      - label: "Banner"
        name: "banner"
        widget: "object"
        fields:
          - {name: "bannerTitle", label: "Banner Title", required: true, widget: "text" }
          - {label: "OfferBanner", name: "offerBanner", widget: "string"}
          - {label: "DescriptionBanner", name: "descriptionBanner", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
      - label: "Looking For Section"
        name: "lookingForSection"
        widget: "object"
        fields:
          - {name: "title", label: "Title", required: true, widget: "text" }
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Image1", name: "image1", widget: "image"}
          - {name: "title2", label: "Title", required: true, widget: "text" }
          - {label: "Image2", name: "image2", widget: "image"}
          - {name: "title3", label: "Title", required: true, widget: "text" }
          - {label: "Image3", name: "image3", widget: "image"}
      - label: "Destinations"
        name: "destinations"
        widget: "object"
        fields:
          - {name: "dtitle", label: "Title", required: true, widget: "text" }
          - {label: "Description", name: "ddescription", widget: "string"}
          - {label: "Image1", name: "dimage", widget: "image"}

      